load('ext://deployment', 'deployment_create')

docker_build(
  'redis-service',
  context='.',
  dockerfile='./Dockerfile',
)

deployment_create('redis-service')

k8s_resource(
  workload='redis-service',
  labels='redis-service'
)
