version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
        - 15692:15692

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    network_mode: host
    volumes:
      - ./mosquitto/conf:/mosquitto/conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001

  redis:
    image: redis
    container_name: redis
    command: redis-server
    ports:
      - 6379:6379

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - --web.enable-remote-write-receiver
    ports:
      - '9090:9090'

  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    ports:
      - 3000:3000