version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    network_mode: host
    volumes:
      - ./mosquitto/conf:/mosquitto/conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001

  redis:
    image: redis
    container_name: redis
    command: redis-server
    ports:
      - 6379:6379