load('ext://deployment', 'deployment_create')

docker_build(
  'kube-services',
  context='.',
  dockerfile='./Dockerfile'
)

deployment_create('kube-services')

k8s_resource(
  workload='kube-services',
  labels='kube-services',
  port_forwards=3000
)
