load('ext://deployment', 'deployment_create')

docker_build(
  'mqtt-service',
  context='.',
  dockerfile='./Dockerfile',
)

deployment_create('mqtt-service')

k8s_resource(
  workload='mqtt-service',
  labels='mqtt-service'
)
